language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - 2.1.0
  - 2.2.5
  - 2.3.1
  - 2.3.3
  - 2.4.0
  - ruby-head
before_install:
  # need this for ruby 1.9.3 and rspec
  - gem update --system
  - gem update bundler
