language: ruby
matrix:
  allow_failures:
    - rvm: ruby-head
rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
before_install:
  # need this for ruby 1.9.3 and rspec
  - gem update --system
  - gem update bundler --force
