version: '2'
services:
  gem:
    image: ruby:2.4.0
    depends_on:
      - nyc-geoclient
    volumes:
      - .:/opt/nyc_geo_client
  nyc-geoclient:
    container_name: nyc-geoclient
    image: 'delner/geoclient:16b'
    expose:
      - 8080
